In [13]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, StandardScaler, Normalizer, Binarizer

<b>Dataset Link: </b>https://www.kaggle.com/datasets/rajyellow46/wine-quality

In [14]:
data = pd.read_csv("wine.csv", usecols = ["fixed acidity", "residual sugar"])
data.head()

fixed acidity  residual sugar
0            7.0            20.7
1            6.3             1.6
2            8.1             6.9
3            7.2             8.5
4            7.2             8.5

In [15]:
m_scaler = MinMaxScaler()
scaled_data = m_scaler.fit_transform(data.dropna())
scaled_data

array([[0.26446281, 0.30828221],
       [0.20661157, 0.01533742],
       [0.3553719 , 0.09662577],
       ...,
       [0.20661157, 0.02607362],
       [0.17355372, 0.02147239],
       [0.18181818, 0.04601227]])

In [16]:
s_scaler = StandardScaler()
scaled_data = s_scaler.fit_transform(data.dropna())
scaled_data

array([[-0.1671114 ,  3.2069093 ],
       [-0.70690732, -0.80787363],
       [ 0.68113933,  0.30617608],
       ...,
       [-0.70690732, -0.66073499],
       [-1.01536213, -0.72379441],
       [-0.93824843, -0.38747751]])

In [17]:
normalizer = Normalizer()
scaled_data = normalizer.fit_transform(data.dropna())
scaled_data

array([[0.32034349, 0.94730146],
       [0.96923077, 0.24615385],
       [0.76124323, 0.64846646],
       ...,
       [0.93935732, 0.34293997],
       [0.94706588, 0.32103928],
       [0.85749293, 0.51449576]])

In [18]:
binarizer = Binarizer()
binarizer.fit_transform(data.dropna())

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [1., 1.]])